services:
  db: 
    image: postgres:18.4
    container_name: db
    restart: always
    shm_size: 128mb
    volumes:
      - type: bind
        source: ./db-data
        target: /var/lib/postgresql/18/docker
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?DB password missing}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-candidate-db}
  be:
    container_name: be
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
  fe:
    container_name: fe
