services:
  db:
    ports:
      - 5433:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  fe: 
    ports: 
      - 5173:5173 
    build: 
      context: frontend
      target: development
    develop: 
      watch: 
        - action: sync 
          path: ./frontend
          target: /app
          ignore: 
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
  be:
    build:
      context: ./backend
      target: development

    ports:
      - "8000:8000"

    develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /app/app

        - action: sync
          path: ./backend/main.py
          target: /app/main.py

        - action: rebuild
          path: ./backend/pyproject.toml

        - action: rebuild
          path: ./backend/uv.lock
