services:
  db: 
    image: postgres:18.4
    container_name: db
    restart: always
    shm_size: 128mb
    volumes:
      - type: bind
        source: ./db-data
        target: /var/lib/postgresql/18/docker
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD:?DB password missing}
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_DB: ${pg_db:-candidate-db}
